export enum ActionTypes {
  SET_CHARACTERS = "SET_CHARACTER",
  SET_SELECTED_CHARACTER = "SET_SELECTED_CHARACTER",
  EDIT_SELECTED_CHARACTER = "EDIT_SELECTED_CHARACTER",
  SET_SERIES = "SET_SERIES",
}
